file_format: "1"
id: cresk_choc_nrf52833
name: cresk_choc_nrf52833
url: https://github.com/nguyendown/cresk
type: board
arch: arm
features:
  - keys
outputs:
  - usb
  - ble
siblings:
  - cresk_choc_nrf52833_left
  - cresk_choc_nrf52833_right
